[build-system]

requires = [
    "setuptools",
    "setuptools_scm",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja",
    "ecl",
    "conan==1.52.0",
    "pybind11>=2.8.1"  # If this comes out of sync with the version installed by Conan please update the version in CMakeLists
]

[tool.pytest.ini_options]
markers = [
    "requires_ert_storage",
    "script",
    "requires_window_manager",
    "consumer_driven_contract_test",
    "unstable",
    "consumer_driven_contract_verification",
    "integration_test"
]
